name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore Projetc.TechChallenge.FIAP/Projetc.TechChallenge.FIAP/Projetc.TechChallenge.FIAP.csproj

    - name: Build
      run: dotnet build Projetc.TechChallenge.FIAP/Projetc.TechChallenge.FIAP/Projetc.TechChallenge.FIAP.csproj --configuration Release 

    - name: Test
      run: dotnet test Projetc.TechChallenge.FIAP/Projetc.TechChallenge.FIAP.IntegrationTest/Projetc.TechChallenge.FIAP.IntegrationTest.csproj  --no-restore --verbosity normal
